---
# Hosts file for home lab and basic infrastructure
# Created September 2024

control:
  hosts:
    biz-srv58:
      ansible_host: 192.168.22.58
    localhost:

pocketnet:
  hosts:
    pocketnet-node11:  # pocketnet-node11
      ansible_host: 192.168.12.35
    pocketnet-node12:  # pocketnet-node12
      ansible_host: 192.168.12.36

checkpoint_distribution:
  hosts:
    checkpoint:  # FTP Server
      ansible_host: 192.168.12.11

nameservers_public:
  hosts:
    137.184.71.119:   #  ns1.biztocloud.com
    24.199.114.146:   #  ns2.biztocloud.com

ubuntu_hosts_new:
  hosts:
    192.168.22.57:
  vars:
    ansible_user: sysadmin

#These hosts are from the Youtube Training videos.  .56 is a bare fresh install of Server 2022
windows_hosts_yt:
  hosts:
    192.168.22.56:  
  vars: 
    ansible_connection: winrm 
    ansible_user: Administrator

windows_hosts_wks:
  hosts:
    192.168.22.60:
    192.168.22.61:
  vars:
    ansible_user: sysadmin 
    ansible_connection: winrm 

windows_hosts_srv:
  hosts:
    10.168.32.36:
  vars:
    ansible_user: sysadmin 
    ansible_connection: winrm 

ubuntu_hosts_srv:
  hosts:
    biz-mta63.inf.biztocloud.com
  vars:
    ansible_user: sysadmin
    


windows_hosts_gra:
  hosts:
    192.168.22.181:
    192.168.22.182:
  vars:
    ansible_user: corp1\sysadmin 
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_port: 5985

fortigate_biz:
  hosts:
    fw01.corp.biztocloud.com:
      ansible_host: 192.168.22.1
